# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

#fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: no-commit-to-branch
      - id: pretty-format-json
        args: ["--autofix", "--indent", "4"]
      - id: fix-encoding-pragma
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.7
    hooks:
      - id: remove-crlf
      - id: forbid-crlf
      - id: remove-tabs
      - id: forbid-tabs

  - repo: https://github.com/google/yapf
    rev: v.40.0
    hooks:
      - id: yapf
        name: yapf
        language: python
        entry: yapf
        args: [-i, -vv]
        types: [python]
        additional_dependencies: ["toml"]
